#!/usr/bin/env python3
"""
Demo script showing how main.py works for tennis set predictions

This demonstrates the CSV management and multiple daily runs functionality.
"""

import os
import time
from datetime import datetime

def demo_main_usage():
    """Demonstrate how main.py handles CSV files and multiple runs"""
    print("🎾 DEMO: MAIN.PY USAGE FOR TENNIS SET PREDICTIONS")
    print("=" * 60)
    print()
    
    print("📋 MAIN.PY FEATURES:")
    print("   ✅ Runs complete tennis set prediction analysis")
    print("   ✅ Writes results to tennis_predictions.csv (overwrites each run)")
    print("   ✅ Creates timestamped archive copies for history")
    print("   ✅ Can be run multiple times per day")
    print("   ✅ Automatic cleanup of old archive files (30+ days)")
    print()
    
    print("💻 USAGE EXAMPLES:")
    print("=" * 30)
    
    print("1️⃣ RUN AUTOMATIC 2-DAY ANALYSIS:")
    print("   python main.py")
    print("   └── Automatically analyzes TODAY + TOMORROW matches")
    print("   └── Writes combined results to tennis_predictions.csv")
    print("   └── Archives to prediction_archive/tennis_predictions_20250120_143022.csv")
    print("   └── No arguments needed - fully automatic!"))
    print()
    
    print("3️⃣ MULTIPLE DAILY RUNS:")
    print("   # Morning run (9 AM)")
    print("   python main.py")
    print("   → Creates: tennis_predictions_20250120_090015.csv")
    print()
    print("   # Afternoon run (2 PM) - new markets available")
    print("   python main.py")
    print("   → Overwrites: tennis_predictions.csv")
    print("   → Creates: tennis_predictions_20250120_140022.csv")
    print()
    print("   # Evening run (6 PM) - final check before betting")
    print("   python main.py")  
    print("   → Overwrites: tennis_predictions.csv") 
    print("   → Creates: tennis_predictions_20250120_180033.csv")
    print()
    
    print("📊 CSV FILE MANAGEMENT:")
    print("=" * 35)
    print("📄 tennis_predictions.csv")
    print("   • Current/latest predictions (always fresh)")
    print("   • Gets overwritten each run")
    print("   • Use this for immediate betting decisions")
    print()
    print("📁 prediction_archive/")
    print("   • tennis_predictions_20250120_090015.csv")
    print("   • tennis_predictions_20250120_140022.csv")
    print("   • tennis_predictions_20250120_180033.csv")
    print("   • Historical record of all runs")
    print("   • Compare predictions over time")
    print("   • Track betting performance")
    print()
    
    print("🎯 TYPICAL DAILY WORKFLOW:")
    print("=" * 35)
    print("🌅 MORNING (9 AM):")
    print("   python main.py")
    print("   → Review high confidence predictions")
    print("   → Plan betting strategy for the day")
    print()
    print("🌞 AFTERNOON (2 PM):")
    print("   python main.py")
    print("   → Check for new matches added")
    print("   → Updated odds and market changes")
    print("   → Adjust betting positions")
    print()
    print("🌆 EVENING (6 PM):")
    print("   python main.py")
    print("   → Final predictions before major betting")
    print("   → Last-minute form/injury updates")
    print("   → Execute betting decisions")
    print()
    
    print("📈 OUTPUT EXAMPLE:")
    print("=" * 25)
    print("🔥 HIGH CONFIDENCE +1.5 SETS RECOMMENDATIONS:")
    print()
    print("   1. 🎾 Stefanos Tsitsipas vs Yunchaokete Bu")
    print("      📍 Australian Open (Hard)")
    print("      🎯 RECOMMENDATION: Stefanos Tsitsipas +1.5 sets")
    print("      📈 Probability: 74.2%")
    print("      💰 Odds: 1.88 / 1.14")
    print("      📊 Reasoning: Better set performance (65% vs 45%), higher ranking...")
    print()
    print("   2. 🎾 Carlos Alcaraz vs Jannik Sinner")
    print("      📍 Roland Garros (Clay)")  
    print("      🎯 RECOMMENDATION: Carlos Alcaraz +1.5 sets")
    print("      📈 Probability: 68.9%")
    print("      💰 Odds: 2.10 / 1.75")
    print("      📊 Reasoning: Superior clay court performance, clutch factor...")
    print()
    
    print("✅ BENEFITS OF THIS SYSTEM:")
    print("=" * 40)
    print("   🎯 Always fresh predictions (overwrites current CSV)")
    print("   📚 Complete historical record (timestamped archives)")
    print("   🔄 Multiple daily runs capture market changes")
    print("   📊 Track betting performance over time")
    print("   🗑️ Automatic cleanup prevents disk space issues")
    print("   💻 Simple command-line interface")
    print("   📈 High/Medium/Low confidence levels")
    print("   💰 Real OddsProvider odds integration")
    print()
    
    print("🚀 READY TO START:")
    print("=" * 25)
    print("1. Run: python main.py")
    print("2. Review tennis_predictions.csv")
    print("3. Place +1.5 sets bets based on high confidence predictions")
    print("4. Run again throughout the day for updates")
    print("5. Track results using archived prediction files")
    print()
    print("🎾💰 Good luck with your tennis set predictions!")

if __name__ == "__main__":
    demo_main_usage()
